import { Navbar } from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Open_Sans } from "next/font/google";
import "slick-carousel/slick/slick.css";
import Footer from "@/components/Footer";
import FooterTop from "@/components/FooterTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ShopIT",
  description: "Generated by create next app"
};

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open_sans"
});

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <title>ShopIT</title>
        <meta name="descriptin" content="created by next aapp"></meta>
        <meta name="viewport" content="created by next aapp"></meta>
        <link rel="icon" href="/smallLogo.ico"></link>
      </Head> */}
      <body>
        <main className={`${open_sans.variable} font-sans bg-lightBlue`}>
          <Navbar />
          {children}
          <FooterTop />
          <Footer />
        </main>
      </body>
    </html>
  );
}
